### ISSUE TITLE
prebuild for leveldown-v1.5.0-node-v57

### ISSUE THREAD

**Issue by artin-phares** [Level/leveldown#393]
Getting error while installing latest `pouchdb@6.3.4` which depends on `leveldown@1.5.0`  
Using `node v8.2.1` on `windown 7` and `ubuntu 16.04` (both `x64`)

---

<details>
 <summary>full error (click to expand)</summary>

> leveldown@1.5.0 install d:\Projects\_tmp\microcosm\node_modules\pouchdb\node_modules\leveldown
> prebuild --install
prebuild info begin Prebuild version 4.5.0
prebuild info looking for local prebuild @ prebuilds\leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild info looking for cached prebuild @ C:\Users\Artin\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.5.0-leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild http request GET https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild http 404 https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild WARN install No prebuilt binaries found (target=v8.2.1 arch=x64 platform=win32)
prebuild info install We will now try to compile from source.
prebuild verb starting node-gyp process
prebuild verb execute node-gyp with `node index.js rebuild --target=v8.2.1 --target_arch=x64`
prebuild verb ok
prebuild verb ok
prebuild verb ok
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to
an invalid version number. [d:\Projects\_tmp\microcosm\node_modules\pouchdb\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [d:\Projects\_tmp\microcosm\node_modules\pouchdb\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to
an invalid version number. [d:\Projects\_tmp\microcosm\node_modules\pouchdb\node_modules\leveldown\deps\snappy\snappy.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [d:\Projects\_tmp\microcosm\node_modules\pouchdb\node_modules\leveldown\deps\snappy\snappy.vcxproj]

</details>

---

So I need `leveldown-v1.5.0-node-v57-win32-x64.tar.gz` and `leveldown-v1.5.0-node-v57-linux-x64.tar.gz`.  
Could you please upload them?

**Comment by ralphtheninja** [comment]
Unfortunately we don't have any good way of rebuilding older versions of leveldown as new node versions come out. I could fix this for linux, but can't help out with windows.

**Comment by ralphtheninja** [comment]
https://github.com/Level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-v57-linux-x64.tar.gz

**Comment by artin-phares** [comment]
Thanks for linux version.  

Btw, is setting up prebuild environment is hard for everyone, or it's just problem with me?  
I've tried to google and setup all those components to build locally on windows.  

But spent 3 hours installing .net, visual studio, etc. but build errors do not want to end up (in fact now I have more weird errors then from the start, msbuild versioning errors clearly want me to suicide).

**Comment by ralphtheninja** [comment]
@artin-phares A prebuild environment is _just_ a build environment. And yes, it's notoriously difficult to get it working on windows.

**Comment by ralphtheninja** [comment]
@vweevers Would it be possible to run this on appveyor somehow for `1.5.0`?

**Comment by vweevers** [comment]
@artin-phares setting up a build environment is a one-liner with [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools):

```
npm install --global --production windows-build-tools
```

@ralphtheninja 

> Would it be possible to run this on appveyor somehow for 1.5.0?

There is a way to trigger a build for any commit IIRC, through AppVeyor's API. I think I wrote a tool for this but don't have it with me (traveling). Will check in the weekend.

If that doesn't pan out I can make a prebuild manually

**Comment by ralphtheninja** [comment]
> `npm install --global --production windows-build-tools`

Aaaah right. Forgot about that one. It _used_ to be difficult :wink:

**Comment by ralphtheninja** [comment]
> There is a way to trigger a build for any commit IIRC, through AppVeyor's API. I think I wrote a tool for this but don't have it with me (traveling). Will check in the weekend.

Maybe it's enough to just re-trigger the build on e.g. travis/appveyor for a particular commit and automatically get new prebuilts made for new versions of node.

**Comment by vweevers** [comment]
The difficulty is in overriding `appveyor.yml` (you need the latest configuration, not the `appveyor.yml` of that particular commit).

**Comment by artin-phares** [comment]
@vweevers 

> setting up a build environment is a one-liner with windows-build-tools

One-liner is perfect. Thanks.  

Although it does not help me to build `leveldown`.
Still seeing good old `MSB8003: Could not find WindowsSDKDir variable from the registry`

**Comment by vweevers** [comment]
@artin-phares we'll try to make prebuilds for you.

@ralphtheninja I think we can trigger prebuilds for 1.5.0 by doing a PR (not from an external branch) that changes `appveyor.yml` to the below. We can even add additional tags to the matrix. Before I push this upstream, do you mind going over it? I don't want it to have side-effects.

```yaml
version: "{build}"
build: off
skip_tags: true
shallow_clone: false

environment:
  matrix:
    - nodejs_version: "8"
      git_tag: "v1.5.0"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: if ($env:nodejs_version -eq "5") { npm i npm@latest -g }
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - git fetch --unshallow --tags
  - git checkout %git_tag%
  - npm i
  - ps: if (!(Test-Path .\node_modules\.bin\prebuild-ci.cmd)) { npm i prebuild-ci }

test_script:
  - npm test
  - ps: if ($(node -p "require('./package.json').scripts.test.indexOf('prebuild-ci')") -eq "-1") { prebuild-ci }
```
